import os
from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph


def generate_pdf(report_data):

    # Create folder if it doesn't exist
    os.makedirs("generated_reports", exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    crop_name = report_data.get("crop", "Unknown").replace(" ", "_")

    filename = f"generated_reports/{crop_name}_{timestamp}.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    # Title
    elements.append(Paragraph("<b><font size=18>🌿 SURAKSHIT FASAL AI REPORT</font></b>", styles["Title"]))

    elements.append(Paragraph("<br/>", styles["Normal"]))

    # Crop Details
    elements.append(Paragraph("<b>Crop:</b> " + report_data.get("crop", "N/A"), styles["Normal"]))
    elements.append(Paragraph("<b>Disease:</b> " + report_data.get("disease", "N/A"), styles["Normal"]))
    elements.append(Paragraph("<b>Confidence:</b> " + report_data.get("confidence", "N/A"), styles["Normal"]))
    elements.append(Paragraph("<b>Severity:</b> " + report_data.get("severity", "N/A"), styles["Normal"]))

    elements.append(Paragraph("<br/>", styles["Normal"]))

    # Recommendation
    elements.append(Paragraph("<b>Recommended Pesticide:</b>", styles["Heading2"]))
    elements.append(Paragraph(report_data.get("recommendation", "N/A"), styles["Normal"]))

    elements.append(Paragraph("<b>Dosage:</b> " + report_data.get("dosage", "N/A"), styles["Normal"]))

    elements.append(Paragraph("<b>PPE / Precautions:</b> " + report_data.get("precautions", "N/A"), styles["Normal"]))

    elements.append(
        Paragraph(
            "<b>Harvest Waiting Period:</b> "
            + report_data.get("harvest_waiting_period", "N/A"),
            styles["Normal"],
        )
    )

    elements.append(Paragraph("<br/>", styles["Normal"]))

    # Weather
    weather = report_data.get("weather", {})

    elements.append(Paragraph("<b>Weather Information</b>", styles["Heading2"]))

    elements.append(Paragraph("<b>City:</b> " + report_data.get("city", "N/A"), styles["Normal"]))

    elements.append(
        Paragraph(
            "<b>Temperature:</b> "
            + str(weather.get("temperature", "N/A"))
            + " °C",
            styles["Normal"],
        )
    )

    elements.append(
        Paragraph(
            "<b>Humidity:</b> "
            + str(weather.get("humidity", "N/A"))
            + " %",
            styles["Normal"],
        )
    )

    elements.append(
        Paragraph(
            "<b>Condition:</b> "
            + str(weather.get("condition", "N/A")),
            styles["Normal"],
        )
    )

    elements.append(Paragraph("<br/>", styles["Normal"]))

    elements.append(
        Paragraph(
            "<b>Weather Advice:</b><br/>"
            + report_data.get("weather_advice", "N/A"),
            styles["Normal"],
        )
    )

    elements.append(Paragraph("<br/>", styles["Normal"]))

    elements.append(
        Paragraph(
            "<b>Generated On:</b> "
            + datetime.now().strftime("%d-%m-%Y %H:%M"),
            styles["Normal"],
        )
    )

    elements.append(Paragraph("<br/>", styles["Normal"]))

    elements.append(
        Paragraph(
            "<font size=10><i>Generated by Surakshit Fasal AI</i></font>",
            styles["Normal"],
        )
    )

    doc.build(elements)

    return filename